// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.2
// source: internal/netproto/game.proto

package netproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityKind int32

const (
	EntityKind_ENTITY_KIND_UNKNOWN       EntityKind = 0
	EntityKind_ENTITY_KIND_PLAYER        EntityKind = 1
	EntityKind_ENTITY_KIND_ENEMY         EntityKind = 2
	EntityKind_ENTITY_KIND_BULLET_PLAYER EntityKind = 3
	EntityKind_ENTITY_KIND_BULLET_ENEMY  EntityKind = 4
)

// Enum value maps for EntityKind.
var (
	EntityKind_name = map[int32]string{
		0: "ENTITY_KIND_UNKNOWN",
		1: "ENTITY_KIND_PLAYER",
		2: "ENTITY_KIND_ENEMY",
		3: "ENTITY_KIND_BULLET_PLAYER",
		4: "ENTITY_KIND_BULLET_ENEMY",
	}
	EntityKind_value = map[string]int32{
		"ENTITY_KIND_UNKNOWN":       0,
		"ENTITY_KIND_PLAYER":        1,
		"ENTITY_KIND_ENEMY":         2,
		"ENTITY_KIND_BULLET_PLAYER": 3,
		"ENTITY_KIND_BULLET_ENEMY":  4,
	}
)

func (x EntityKind) Enum() *EntityKind {
	p := new(EntityKind)
	*p = x
	return p
}

func (x EntityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_netproto_game_proto_enumTypes[0].Descriptor()
}

func (EntityKind) Type() protoreflect.EnumType {
	return &file_internal_netproto_game_proto_enumTypes[0]
}

func (x EntityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityKind.Descriptor instead.
func (EntityKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{0}
}

type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_internal_netproto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type JoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReq) Reset() {
	*x = JoinReq{}
	mi := &file_internal_netproto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReq) ProtoMessage() {}

func (x *JoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReq.ProtoReflect.Descriptor instead.
func (*JoinReq) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{1}
}

func (x *JoinReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     uint64                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UdpPort       uint32                 `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"`
	TickHz        uint32                 `protobuf:"varint,4,opt,name=tick_hz,json=tickHz,proto3" json:"tick_hz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResp) Reset() {
	*x = JoinResp{}
	mi := &file_internal_netproto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResp) ProtoMessage() {}

func (x *JoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResp.ProtoReflect.Descriptor instead.
func (*JoinResp) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResp) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *JoinResp) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *JoinResp) GetUdpPort() uint32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

func (x *JoinResp) GetTickHz() uint32 {
	if x != nil {
		return x.TickHz
	}
	return 0
}

type ErrorMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	mi := &file_internal_netproto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorMsg) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameOver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	mi := &file_internal_netproto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameOver) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GameOver) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TcpEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*TcpEnvelope_JoinReq
	//	*TcpEnvelope_JoinResp
	//	*TcpEnvelope_Error
	//	*TcpEnvelope_GameOver
	Msg           isTcpEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpEnvelope) Reset() {
	*x = TcpEnvelope{}
	mi := &file_internal_netproto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpEnvelope) ProtoMessage() {}

func (x *TcpEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpEnvelope.ProtoReflect.Descriptor instead.
func (*TcpEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{5}
}

func (x *TcpEnvelope) GetMsg() isTcpEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *TcpEnvelope) GetJoinReq() *JoinReq {
	if x != nil {
		if x, ok := x.Msg.(*TcpEnvelope_JoinReq); ok {
			return x.JoinReq
		}
	}
	return nil
}

func (x *TcpEnvelope) GetJoinResp() *JoinResp {
	if x != nil {
		if x, ok := x.Msg.(*TcpEnvelope_JoinResp); ok {
			return x.JoinResp
		}
	}
	return nil
}

func (x *TcpEnvelope) GetError() *ErrorMsg {
	if x != nil {
		if x, ok := x.Msg.(*TcpEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *TcpEnvelope) GetGameOver() *GameOver {
	if x != nil {
		if x, ok := x.Msg.(*TcpEnvelope_GameOver); ok {
			return x.GameOver
		}
	}
	return nil
}

type isTcpEnvelope_Msg interface {
	isTcpEnvelope_Msg()
}

type TcpEnvelope_JoinReq struct {
	JoinReq *JoinReq `protobuf:"bytes,1,opt,name=join_req,json=joinReq,proto3,oneof"`
}

type TcpEnvelope_JoinResp struct {
	JoinResp *JoinResp `protobuf:"bytes,2,opt,name=join_resp,json=joinResp,proto3,oneof"`
}

type TcpEnvelope_Error struct {
	Error *ErrorMsg `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type TcpEnvelope_GameOver struct {
	GameOver *GameOver `protobuf:"bytes,4,opt,name=game_over,json=gameOver,proto3,oneof"`
}

func (*TcpEnvelope_JoinReq) isTcpEnvelope_Msg() {}

func (*TcpEnvelope_JoinResp) isTcpEnvelope_Msg() {}

func (*TcpEnvelope_Error) isTcpEnvelope_Msg() {}

func (*TcpEnvelope_GameOver) isTcpEnvelope_Msg() {}

type UdpHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpHello) Reset() {
	*x = UdpHello{}
	mi := &file_internal_netproto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpHello) ProtoMessage() {}

func (x *UdpHello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpHello.ProtoReflect.Descriptor instead.
func (*UdpHello) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{6}
}

func (x *UdpHello) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type InputFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputSeq      uint32                 `protobuf:"varint,1,opt,name=input_seq,json=inputSeq,proto3" json:"input_seq,omitempty"`
	MoveX         int32                  `protobuf:"varint,2,opt,name=move_x,json=moveX,proto3" json:"move_x,omitempty"`
	MoveY         int32                  `protobuf:"varint,3,opt,name=move_y,json=moveY,proto3" json:"move_y,omitempty"`
	Fire          bool                   `protobuf:"varint,4,opt,name=fire,proto3" json:"fire,omitempty"`
	AimDx         float32                `protobuf:"fixed32,5,opt,name=aim_dx,json=aimDx,proto3" json:"aim_dx,omitempty"`
	AimDy         float32                `protobuf:"fixed32,6,opt,name=aim_dy,json=aimDy,proto3" json:"aim_dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFrame) Reset() {
	*x = InputFrame{}
	mi := &file_internal_netproto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFrame) ProtoMessage() {}

func (x *InputFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFrame.ProtoReflect.Descriptor instead.
func (*InputFrame) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{7}
}

func (x *InputFrame) GetInputSeq() uint32 {
	if x != nil {
		return x.InputSeq
	}
	return 0
}

func (x *InputFrame) GetMoveX() int32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *InputFrame) GetMoveY() int32 {
	if x != nil {
		return x.MoveY
	}
	return 0
}

func (x *InputFrame) GetFire() bool {
	if x != nil {
		return x.Fire
	}
	return false
}

func (x *InputFrame) GetAimDx() float32 {
	if x != nil {
		return x.AimDx
	}
	return 0
}

func (x *InputFrame) GetAimDy() float32 {
	if x != nil {
		return x.AimDy
	}
	return 0
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetId         uint32                 `protobuf:"varint,1,opt,name=net_id,json=netId,proto3" json:"net_id,omitempty"`
	Kind          EntityKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=game.EntityKind" json:"kind,omitempty"`
	OwnerPlayerId uint32                 `protobuf:"varint,3,opt,name=owner_player_id,json=ownerPlayerId,proto3" json:"owner_player_id,omitempty"`
	Pos           *Vec2                  `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Vel           *Vec2                  `protobuf:"bytes,5,opt,name=vel,proto3" json:"vel,omitempty"`
	Hp            int32                  `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Radius        float32                `protobuf:"fixed32,7,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_internal_netproto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{8}
}

func (x *EntityState) GetNetId() uint32 {
	if x != nil {
		return x.NetId
	}
	return 0
}

func (x *EntityState) GetKind() EntityKind {
	if x != nil {
		return x.Kind
	}
	return EntityKind_ENTITY_KIND_UNKNOWN
}

func (x *EntityState) GetOwnerPlayerId() uint32 {
	if x != nil {
		return x.OwnerPlayerId
	}
	return 0
}

func (x *EntityState) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityState) GetVel() *Vec2 {
	if x != nil {
		return x.Vel
	}
	return nil
}

func (x *EntityState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityState) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type ImpactEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BulletNetId     uint32                 `protobuf:"varint,1,opt,name=bullet_net_id,json=bulletNetId,proto3" json:"bullet_net_id,omitempty"`
	BulletKind      EntityKind             `protobuf:"varint,2,opt,name=bullet_kind,json=bulletKind,proto3,enum=game.EntityKind" json:"bullet_kind,omitempty"`
	SourcePlayerId  uint32                 `protobuf:"varint,3,opt,name=source_player_id,json=sourcePlayerId,proto3" json:"source_player_id,omitempty"`
	TargetNetId     uint32                 `protobuf:"varint,4,opt,name=target_net_id,json=targetNetId,proto3" json:"target_net_id,omitempty"`
	TargetKind      EntityKind             `protobuf:"varint,5,opt,name=target_kind,json=targetKind,proto3,enum=game.EntityKind" json:"target_kind,omitempty"`
	Pos             *Vec2                  `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
	Damage          int32                  `protobuf:"varint,7,opt,name=damage,proto3" json:"damage,omitempty"`
	TargetDestroyed bool                   `protobuf:"varint,8,opt,name=target_destroyed,json=targetDestroyed,proto3" json:"target_destroyed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImpactEvent) Reset() {
	*x = ImpactEvent{}
	mi := &file_internal_netproto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactEvent) ProtoMessage() {}

func (x *ImpactEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactEvent.ProtoReflect.Descriptor instead.
func (*ImpactEvent) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{9}
}

func (x *ImpactEvent) GetBulletNetId() uint32 {
	if x != nil {
		return x.BulletNetId
	}
	return 0
}

func (x *ImpactEvent) GetBulletKind() EntityKind {
	if x != nil {
		return x.BulletKind
	}
	return EntityKind_ENTITY_KIND_UNKNOWN
}

func (x *ImpactEvent) GetSourcePlayerId() uint32 {
	if x != nil {
		return x.SourcePlayerId
	}
	return 0
}

func (x *ImpactEvent) GetTargetNetId() uint32 {
	if x != nil {
		return x.TargetNetId
	}
	return 0
}

func (x *ImpactEvent) GetTargetKind() EntityKind {
	if x != nil {
		return x.TargetKind
	}
	return EntityKind_ENTITY_KIND_UNKNOWN
}

func (x *ImpactEvent) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *ImpactEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *ImpactEvent) GetTargetDestroyed() bool {
	if x != nil {
		return x.TargetDestroyed
	}
	return false
}

type Snapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Tick                  uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	LastProcessedInputSeq uint32                 `protobuf:"varint,2,opt,name=last_processed_input_seq,json=lastProcessedInputSeq,proto3" json:"last_processed_input_seq,omitempty"`
	Score                 int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Running               bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	Entities              []*EntityState         `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	Impacts               []*ImpactEvent         `protobuf:"bytes,6,rep,name=impacts,proto3" json:"impacts,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_internal_netproto_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{10}
}

func (x *Snapshot) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Snapshot) GetLastProcessedInputSeq() uint32 {
	if x != nil {
		return x.LastProcessedInputSeq
	}
	return 0
}

func (x *Snapshot) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Snapshot) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Snapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetImpacts() []*ImpactEvent {
	if x != nil {
		return x.Impacts
	}
	return nil
}

type UdpEnvelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*UdpEnvelope_Hello
	//	*UdpEnvelope_Input
	//	*UdpEnvelope_Snapshot
	Msg           isUdpEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpEnvelope) Reset() {
	*x = UdpEnvelope{}
	mi := &file_internal_netproto_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpEnvelope) ProtoMessage() {}

func (x *UdpEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_netproto_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpEnvelope.ProtoReflect.Descriptor instead.
func (*UdpEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_netproto_game_proto_rawDescGZIP(), []int{11}
}

func (x *UdpEnvelope) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UdpEnvelope) GetMsg() isUdpEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *UdpEnvelope) GetHello() *UdpHello {
	if x != nil {
		if x, ok := x.Msg.(*UdpEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *UdpEnvelope) GetInput() *InputFrame {
	if x != nil {
		if x, ok := x.Msg.(*UdpEnvelope_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *UdpEnvelope) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Msg.(*UdpEnvelope_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isUdpEnvelope_Msg interface {
	isUdpEnvelope_Msg()
}

type UdpEnvelope_Hello struct {
	Hello *UdpHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type UdpEnvelope_Input struct {
	Input *InputFrame `protobuf:"bytes,11,opt,name=input,proto3,oneof"`
}

type UdpEnvelope_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,12,opt,name=snapshot,proto3,oneof"`
}

func (*UdpEnvelope_Hello) isUdpEnvelope_Msg() {}

func (*UdpEnvelope_Input) isUdpEnvelope_Msg() {}

func (*UdpEnvelope_Snapshot) isUdpEnvelope_Msg() {}

var File_internal_netproto_game_proto protoreflect.FileDescriptor

const file_internal_netproto_game_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/netproto/game.proto\x12\x04game\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\x1d\n" +
	"\aJoinReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"z\n" +
	"\bJoinResp\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x04R\tsessionId\x12\x19\n" +
	"\budp_port\x18\x03 \x01(\rR\audpPort\x12\x17\n" +
	"\atick_hz\x18\x04 \x01(\rR\x06tickHz\"8\n" +
	"\bErrorMsg\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\bGameOver\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"\xc6\x01\n" +
	"\vTcpEnvelope\x12*\n" +
	"\bjoin_req\x18\x01 \x01(\v2\r.game.JoinReqH\x00R\ajoinReq\x12-\n" +
	"\tjoin_resp\x18\x02 \x01(\v2\x0e.game.JoinRespH\x00R\bjoinResp\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x0e.game.ErrorMsgH\x00R\x05error\x12-\n" +
	"\tgame_over\x18\x04 \x01(\v2\x0e.game.GameOverH\x00R\bgameOverB\x05\n" +
	"\x03msg\")\n" +
	"\bUdpHello\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\"\x99\x01\n" +
	"\n" +
	"InputFrame\x12\x1b\n" +
	"\tinput_seq\x18\x01 \x01(\rR\binputSeq\x12\x15\n" +
	"\x06move_x\x18\x02 \x01(\x05R\x05moveX\x12\x15\n" +
	"\x06move_y\x18\x03 \x01(\x05R\x05moveY\x12\x12\n" +
	"\x04fire\x18\x04 \x01(\bR\x04fire\x12\x15\n" +
	"\x06aim_dx\x18\x05 \x01(\x02R\x05aimDx\x12\x15\n" +
	"\x06aim_dy\x18\x06 \x01(\x02R\x05aimDy\"\xd6\x01\n" +
	"\vEntityState\x12\x15\n" +
	"\x06net_id\x18\x01 \x01(\rR\x05netId\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.game.EntityKindR\x04kind\x12&\n" +
	"\x0fowner_player_id\x18\x03 \x01(\rR\rownerPlayerId\x12\x1c\n" +
	"\x03pos\x18\x04 \x01(\v2\n" +
	".game.Vec2R\x03pos\x12\x1c\n" +
	"\x03vel\x18\x05 \x01(\v2\n" +
	".game.Vec2R\x03vel\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x05R\x02hp\x12\x16\n" +
	"\x06radius\x18\a \x01(\x02R\x06radius\"\xc6\x02\n" +
	"\vImpactEvent\x12\"\n" +
	"\rbullet_net_id\x18\x01 \x01(\rR\vbulletNetId\x121\n" +
	"\vbullet_kind\x18\x02 \x01(\x0e2\x10.game.EntityKindR\n" +
	"bulletKind\x12(\n" +
	"\x10source_player_id\x18\x03 \x01(\rR\x0esourcePlayerId\x12\"\n" +
	"\rtarget_net_id\x18\x04 \x01(\rR\vtargetNetId\x121\n" +
	"\vtarget_kind\x18\x05 \x01(\x0e2\x10.game.EntityKindR\n" +
	"targetKind\x12\x1c\n" +
	"\x03pos\x18\x06 \x01(\v2\n" +
	".game.Vec2R\x03pos\x12\x16\n" +
	"\x06damage\x18\a \x01(\x05R\x06damage\x12)\n" +
	"\x10target_destroyed\x18\b \x01(\bR\x0ftargetDestroyed\"\xe3\x01\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x127\n" +
	"\x18last_processed_input_seq\x18\x02 \x01(\rR\x15lastProcessedInputSeq\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\x12-\n" +
	"\bentities\x18\x05 \x03(\v2\x11.game.EntityStateR\bentities\x12+\n" +
	"\aimpacts\x18\x06 \x03(\v2\x11.game.ImpactEventR\aimpacts\"\xb3\x01\n" +
	"\vUdpEnvelope\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12&\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x0e.game.UdpHelloH\x00R\x05hello\x12(\n" +
	"\x05input\x18\v \x01(\v2\x10.game.InputFrameH\x00R\x05input\x12,\n" +
	"\bsnapshot\x18\f \x01(\v2\x0e.game.SnapshotH\x00R\bsnapshotB\x05\n" +
	"\x03msg*\x91\x01\n" +
	"\n" +
	"EntityKind\x12\x17\n" +
	"\x13ENTITY_KIND_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ENTITY_KIND_PLAYER\x10\x01\x12\x15\n" +
	"\x11ENTITY_KIND_ENEMY\x10\x02\x12\x1d\n" +
	"\x19ENTITY_KIND_BULLET_PLAYER\x10\x03\x12\x1c\n" +
	"\x18ENTITY_KIND_BULLET_ENEMY\x10\x04B&Z$agentDemo/internal/netproto;netprotob\x06proto3"

var (
	file_internal_netproto_game_proto_rawDescOnce sync.Once
	file_internal_netproto_game_proto_rawDescData []byte
)

func file_internal_netproto_game_proto_rawDescGZIP() []byte {
	file_internal_netproto_game_proto_rawDescOnce.Do(func() {
		file_internal_netproto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_netproto_game_proto_rawDesc), len(file_internal_netproto_game_proto_rawDesc)))
	})
	return file_internal_netproto_game_proto_rawDescData
}

var file_internal_netproto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_netproto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_netproto_game_proto_goTypes = []any{
	(EntityKind)(0),     // 0: game.EntityKind
	(*Vec2)(nil),        // 1: game.Vec2
	(*JoinReq)(nil),     // 2: game.JoinReq
	(*JoinResp)(nil),    // 3: game.JoinResp
	(*ErrorMsg)(nil),    // 4: game.ErrorMsg
	(*GameOver)(nil),    // 5: game.GameOver
	(*TcpEnvelope)(nil), // 6: game.TcpEnvelope
	(*UdpHello)(nil),    // 7: game.UdpHello
	(*InputFrame)(nil),  // 8: game.InputFrame
	(*EntityState)(nil), // 9: game.EntityState
	(*ImpactEvent)(nil), // 10: game.ImpactEvent
	(*Snapshot)(nil),    // 11: game.Snapshot
	(*UdpEnvelope)(nil), // 12: game.UdpEnvelope
}
var file_internal_netproto_game_proto_depIdxs = []int32{
	2,  // 0: game.TcpEnvelope.join_req:type_name -> game.JoinReq
	3,  // 1: game.TcpEnvelope.join_resp:type_name -> game.JoinResp
	4,  // 2: game.TcpEnvelope.error:type_name -> game.ErrorMsg
	5,  // 3: game.TcpEnvelope.game_over:type_name -> game.GameOver
	0,  // 4: game.EntityState.kind:type_name -> game.EntityKind
	1,  // 5: game.EntityState.pos:type_name -> game.Vec2
	1,  // 6: game.EntityState.vel:type_name -> game.Vec2
	0,  // 7: game.ImpactEvent.bullet_kind:type_name -> game.EntityKind
	0,  // 8: game.ImpactEvent.target_kind:type_name -> game.EntityKind
	1,  // 9: game.ImpactEvent.pos:type_name -> game.Vec2
	9,  // 10: game.Snapshot.entities:type_name -> game.EntityState
	10, // 11: game.Snapshot.impacts:type_name -> game.ImpactEvent
	7,  // 12: game.UdpEnvelope.hello:type_name -> game.UdpHello
	8,  // 13: game.UdpEnvelope.input:type_name -> game.InputFrame
	11, // 14: game.UdpEnvelope.snapshot:type_name -> game.Snapshot
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_netproto_game_proto_init() }
func file_internal_netproto_game_proto_init() {
	if File_internal_netproto_game_proto != nil {
		return
	}
	file_internal_netproto_game_proto_msgTypes[5].OneofWrappers = []any{
		(*TcpEnvelope_JoinReq)(nil),
		(*TcpEnvelope_JoinResp)(nil),
		(*TcpEnvelope_Error)(nil),
		(*TcpEnvelope_GameOver)(nil),
	}
	file_internal_netproto_game_proto_msgTypes[11].OneofWrappers = []any{
		(*UdpEnvelope_Hello)(nil),
		(*UdpEnvelope_Input)(nil),
		(*UdpEnvelope_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_netproto_game_proto_rawDesc), len(file_internal_netproto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_netproto_game_proto_goTypes,
		DependencyIndexes: file_internal_netproto_game_proto_depIdxs,
		EnumInfos:         file_internal_netproto_game_proto_enumTypes,
		MessageInfos:      file_internal_netproto_game_proto_msgTypes,
	}.Build()
	File_internal_netproto_game_proto = out.File
	file_internal_netproto_game_proto_goTypes = nil
	file_internal_netproto_game_proto_depIdxs = nil
}
